# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171103_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
