# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20171004_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
