# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import documents.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='docs', validators=[documents.validators.validate_mime_type])),
                ('name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
