# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='docs', validators=[documents.validators.validate_mime_type]),
        ),
    ]
