# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
