# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delete_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='extra_notes',
        ),
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
